# -*- coding: utf-8 -*-
"""Hangman.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n0r74rIa5Ltej6pPUFmt-oJYz22xnEdW
"""

import random
name=input("What's your name? " )
print("Let's play hangman!!",name)
print("This game is case sensitive")
words=list(D.iloc[:,0]) #.lower
word=random.choice(words)
#word=word.lower()
mean=D.loc[D["Words"]==word].iloc[0,1]
guesses=""
turns=5
while turns>0:
  fail=0
  for letter in word:
    if letter in guesses:
      print(letter)
    else:
      print("-")
      fail+=1
  if fail ==0:
    print("You won!",name)
    print("The word is",word)
    print("The meaning of the word is,",mean)
    break
  guess=input("Guess a letter. ")
  guesses+=guess
  if guess not in word:
    turns-=1
    print("Wrong!")
    print("You have",turns,"guesses left.")
    if turns==0:
      print("You loose :(")
      print("The word was",word)

import pandas as pd
D = pd.read_csv("HW.csv")

D