# -*- coding: utf-8 -*-
"""Random_Numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pbzBRnCMYd9Ya4OA-vswuruqRNC5GvkY
"""

import random # random se utiliza para elegir numeros al azar
digitos = ('0','1','2','3','4','5','6','7','8','9')
numero = ''
for i in range(4):
    candidato = random.choice(digitos)

    while candidato in numero: # digitos no repetidos
        candidato = random.choice(digitos) # Choice es utilizado para una secuencia
    numero = numero + candidato

print ("Welcome to our game!")
print ("You have to guess a number with", 4, "different digits.")
propuesta = input("What number do you propose?: ")

# propuestas de numeros, aciertos y coincidencias
intentos = 1 #contador
while propuesta != numero: # != diferente
    intentos = intentos + 1
    aciertos = 0
    coincidencias = 0
    # verificación del número
    for i in range(4):
        if propuesta[i] == numero[i]: #Si la propuesta es igual al número

            aciertos = aciertos + 1
        elif propuesta[i] in numero:
            coincidencias = coincidencias + 1
    print ("Your proposal ", propuesta, " have", aciertos, "hits and ", coincidencias, "coincidences.")
    # pedir siguiente propuesta*
    propuesta = input("Suggest another number: ")

print ("Congratulations! You guessed the number in", intentos, "hits.")